### PR TITLE
[FEEDBACK]  iOS Segmented Controller

### PR DESCRIPTION
**Pull request by sboddeus**
I have implemented most of the API for `UISegmentedController` and created a page in the iOS catalogue for visual testing. Because this would be my first contribution to this project I just wanted to make sure that my implementation so far fits with your intentions before writing the required unit tests.

For the most part I followed the implementation for macOS's `SegmentedControl`, which means creating a `SegmentDescription` struct for the individual segments. It is this struct and the associated implementation of `applyBinding()` for case `.segments()` that I am looking for feedback on specifically, as I feel this implementation may be restrictive?

### CODE REVIEW

**Comment by mattgallagher** [comment]
I'd had just a quick look but it all seems pretty good to me. I think you've taken the right approach with `SegmentDescription`.

I don't know if you considered using `ArrayMutation<SegmentDescription>` for the `segments` binding argument. It is a little more complex to use – so it shouldn't be used if it offers no benefit – but it would allow the use of `insertionsAndRemovals` to generate specific inserts and removes instead of needing to `removeAllSegments` each time (see `tabs` binding in CwlTabBar_macOS.swift for example). The reason why this might help is if `UISegmentedControl` has specific animation for individual insertion and removal (versus updating all elements) then specific inserts and removes might be required.

I'll try to take a closer look tomorrow to check this and other behaviors but the PR seems solid to me.

**Comment by sboddeus** [comment]
Thank you for the feedback.

I had considered something similar to the `ArrayMutation`, as adding and removing sections is animatable and granular, but did not know there was already an implementation 😅 Very happy to find that there is one.

I have refactored that section to use the `ArrayMutation` and added bindings for the remaining `UISegmentedControl `APIs (consisting of APIs to customise appearance). I will add the unit tests after you are able to check the other behaviours.

**Comment by mattgallagher** [comment]
Thanks for your work on this. I've merged the PR. I did follow up with some minor changes to `SegmentDescription` in cc4b3e6684da92dcc9b4b02912d2b677e8babb00 so that it contains the `title` or `image` in an `enum` (instead of separate optionals), reflecting the fact that you cannot have both at the same time, and I altered the constructors to reflect this. I also moved the setting of the initially selected segment to the `finalizeInstance` function so it is guaranteed to be set after the initial segments are constructed.

**Comment by sboddeus** [comment]
Ahh, that `enum` instead of two constructors is an obviously better solution, thanks :)
And thanks in general for the framework, it is a joy to use.

**Pull request merged**
